name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: Lab5\Lab5.sln                        # Replace with your solution name
      Test_Project_Path: TestProject1\TestProject1.csproj # Replace with your test project path

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

    - name: Run unit tests
      run: dotnet test $env:Test_Project_Path --configuration ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Output
        path: |
          **\bin\${{ matrix.configuration }}\
